package com.tencent.cloud.huiyansdkface.facelight.api;

/* loaded from: source-8457232-dex2jar.jar:com/tencent/cloud/huiyansdkface/facelight/api/WbCloudFaceContant.class */
public class WbCloudFaceContant {
    public static final String BLACK = "black";
    public static final String BLINK_SAFETY = "blinkSafety";
    public static final String CHECK_WILL_VIDEO = "checkWillVideo";
    public static final String COLOR_MODE = "colorMode";
    public static final String COMPARE_TYPE = "compareType";
    public static final String CUSTOM = "custom";
    public static final String CUSTOMER_CAM_REASON = "customerCamReason";
    public static final String CUSTOMER_LONG_TIP = "customerLongTip";
    public static final String CUSTOMER_TIPS_LIVE = "customerTipsInLive";
    public static final String CUSTOMER_TIPS_LOC = "uiType";
    public static final int CUSTOMER_TIPS_LOC_BOTTOM = 0;
    public static final int CUSTOMER_TIPS_LOC_TOP = 1;
    public static final String CUSTOMER_TIPS_UPLOAD = "customerTipsInUpload";
    public static final String CUSTOMER_WILL_PERMISSION_REASON = "customerWillPermissionReason";
    public static final String DIALOG_NO = "dialogNo";
    public static final String DIALOG_TEXT = "dialogText";
    public static final String DIALOG_TITLE = "dialogTitle";
    public static final String DIALOG_YES = "dialogYes";
    public static final String ENABLE_TRACK_LOG = "enableTrackLog";
    public static final String ID_CARD = "idCard";
    public static final String INPUT_DATA = "inputData";
    public static final String IS_ABROAD = "isAbroad";
    public static final String IS_ENABLE_LOG = "isEnableLog";
    public static final String IS_IPV6 = "isIpv6";
    public static final String IS_LANDSCAPE = "isLandscape";
    public static final String IS_SHOW_ENV_CHOOSE = "isShowEnvChoose";
    public static final String IS_SIMPLE_MODE = "isSimpleMode";
    public static final String IS_SIT_ENV = "isSitEnv";
    public static final String IS_UNI = "isUni";
    public static final String LANGUAGE = "WBFaceVerifyLanguage";
    public static final String LANGUAGE_EN = "WBFaceVerifyLanguage_en";
    public static final String LANGUAGE_ID = "WBFaceVerifyLanguage_id";
    public static final String LANGUAGE_JA = "WBFaceVerifyLanguage_ja";
    public static final String LANGUAGE_KO = "WBFaceVerifyLanguage_ko";
    public static final String LANGUAGE_TH = "WBFaceVerifyLanguage_th";
    public static final String LANGUAGE_ZH_CN = "WBFaceVerifyLanguage_zh_cn";
    public static final String LANGUAGE_ZH_HK = "WBFaceVerifyLanguage_zh_hk";
    public static final String NONE = "none";
    public static final String PATH_ENV = "pathEnv";
    public static final String PLAY_VOICE = "playVoice";
    public static final String RECORD_WILL_VIDEO = "recordWillVideo";
    public static final String RETURN_VIDEO = "returnVideo";
    public static final String SWITCH_CAM = "cameraSwitch";
    public static final String UPLOAD_AND_RETURN_WILL_VIDEO = "uploadAndReturnWillVideo";
    public static final String USER_AES_IV = "userAESIv";
    public static final String USER_PUBLIC_KEY = "userPublicKey";
    public static final String VIDEO_CHECK = "videoCheck";
    public static final String VIDEO_UPLOAD = "videoUpload";
    public static final String WHITE = "white";
    public static final String WILL_MAX_PLAY_VOLUME = "willMaxPlayVolume";
    public static final String YT_MODEL_LOC = "ytModelLoc";
}
